[package]
name = "image_blend"
version = "0.1.0"
authors = ["sombrastudios <nils.martel@graphmasters.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.15.0"
